version: "2"
services:
  app:
    env_file:
      - .env
    container_name: api-naffiq-com
    restart: always
    build: .
    ports:
      - "9001:9001"
    links:
      - mongo
  mongo:
    container_name: mongo
    command: mongod --port 27018
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"
